spring:
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/spring-data?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #thymeleaf
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8

mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: com.cicada.domain
  
logging:
  level:
    root: info
